config/routes.rb
Rails.application.routes.draw do
  get "estaticas/contacto"
  get "estaticas/nosotros"
  get "estaticas/otra"

  resources :personas
  get "articulos/new"
  get "articulos/index"
  get "articulos/show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def new
  end

  def index
  end

  def show
  end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
  end

  def nosotros
  end

  def otra
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1 or /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to persona_url(@persona), notice: "Persona was successfully created." }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to persona_url(@persona), notice: "Persona was successfully updated." }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url, notice: "Persona was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:nombre, :edad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

app/views/articulos/show.html.erb
<h1>Articulos#show</h1>
<p>Find me in app/views/articulos/show.html.erb</p>

app/views/estaticas/contacto.html.erb
<h1>Estaticas#contacto</h1>
<p>Find me in app/views/estaticas/contacto.html.erb</p>

app/views/estaticas/nosotros.html.erb
<h1>Estaticas#nosotros</h1>
<p>Find me in app/views/estaticas/nosotros.html.erb</p>

app/views/estaticas/otra.html.erb
<h1>Otra Página</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miblog8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
        <% persona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.edad %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.edad %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>